services:
  dockiup:
    image: dockiup:0.0.1
    container_name: dockiup
    build:
      context: .
      dockerfile: src/DockiUp.API/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__DockiUpDatabase=Server=dockiup-db;Port=3306;Database=dockiupdb;User=root;Password=${MYSQL_ROOT_PASSWORD}
      - SystemPaths__DockerSocket=${DOCKER_SOCKET_PATH}
      - SystemPaths__ProjectsPath=${PROJECTS_PATH}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH}
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dockiup-db:
        condition: service_healthy  # Ensures DB is ready before starting the app

  dockiup-db:
    image: mysql:8.0.34
    container_name: dockiup-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dockiupdb
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:  # Waits until MySQL is ready
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  mysql-data:
