services:
  dockiup:
    image: dockiup:0.0.1
    container_name: dockiup
    build:
      context: .
      dockerfile: src/ArgonFetch.API/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - dockiup-network

  dev-db:
    image: mysql:8.0.34
    container_name: dockiup-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dockiupdb-dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dockiup-network

networks:
  dockiup-network:

volumes:
  mysql-data:
