using System.Text;
using System.Text.RegularExpressions;

namespace DockiUp.Application.Deployments
{
    /// <summary>Builds the env file compose gets via <c>--env-file</c>. Because <c>--env-file</c> replaces
    /// compose's automatic <c>.env</c>, the project's own <c>.env</c> is merged in. Precedence: a variable
    /// mapped to a vault secret wins over the same name in <c>.env</c>; everything else in <c>.env</c> is
    /// kept as is. (Compose itself still lets variables from DockiUp's own process environment win over both.)</summary>
    public static partial class EnvFile
    {
        /// <summary>Generated next to the compose project; the leading dot keeps it out of casual listings.</summary>
        public const string GeneratedFileName = ".dockiup.env";

        [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*$")]
        private static partial Regex NamePattern();

        public static bool IsValidName(string name) => NamePattern().IsMatch(name);

        public static string Merge(string? existing, IReadOnlyDictionary<string, string> secrets)
        {
            var output = new StringBuilder("# Generated by DockiUp at deploy time (.env merged with vault secrets). Do not edit.\n");
            var written = new HashSet<string>(StringComparer.Ordinal);

            foreach (var line in (existing ?? "").ReplaceLineEndings("\n").Split('\n'))
            {
                var key = KeyOf(line);
                if (key is not null && secrets.TryGetValue(key, out var value))
                {
                    // Replace in place, once; a later duplicate of a mapped name would override it in compose.
                    if (written.Add(key)) output.Append(Format(key, value)).Append('\n');
                    continue;
                }
                output.Append(line).Append('\n');
            }

            foreach (var (key, value) in secrets.Where(s => !written.Contains(s.Key)).OrderBy(s => s.Key, StringComparer.Ordinal))
                output.Append(Format(key, value)).Append('\n');
            return output.ToString();
        }

        private static string? KeyOf(string line)
        {
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith("export ", StringComparison.Ordinal)) trimmed = trimmed[7..].TrimStart();
            var eq = trimmed.IndexOf('=');
            return eq > 0 ? trimmed[..eq].Trim() : null;
        }

        // Single quotes are literal in compose's dotenv parser (no ${...} interpolation, no escapes), so use
        // them whenever possible; otherwise double quotes with every special character escaped.
        private static string Format(string key, string value)
        {
            if (!value.Contains('\'') && !value.Contains('\n') && !value.Contains('\r'))
                return $"{key}='{value}'";
            var escaped = value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("$", "\\$");
            return $"{key}=\"{escaped}\"";
        }
    }
}
