/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdoptProjectDtoPeriodicIntervalInMinutes } from './adoptProjectDtoPeriodicIntervalInMinutes';


export interface AdoptProjectDto { 
    dockerProjectName: string;
    nodeId?: string | null;
    description?: string | null;
    projectUpdateMethod: number;
    periodicIntervalInMinutes?: AdoptProjectDtoPeriodicIntervalInMinutes | null;
}

