/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppInfoDto {
    version: string;
    environment: string;
    authority?: string;
    clientId?: string;
    redirectUri?: string;
    postLogoutRedirectUri?: string;
    scope?: string;
    authEnabled?: boolean;
}

