/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ColorScheme = 0 | 1 | 2;

export const ColorScheme = {

    NUMBER_0: 0 as ColorScheme,

    NUMBER_1: 1 as ColorScheme,

    NUMBER_2: 2 as ColorScheme
};

