/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComposeDto { 
    serviceName?: string | null;
    ports?: Array<string> | null;
    environmentVariables?: Array<string> | null;
}

