/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComposeDto } from './composeDto';


export interface ComposeInfoDto { 
    services?: Array<ComposeDto> | null;
}

