/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComposeValidationRequest { 
    nodeId: string | null;
    compose: string | null;
    envFile: string | null;
    gitUrl?: string | null;
    branch?: string | null;
    composeFile?: string | null;
    gitCredentialId?: string | null;
}

