/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContainerStatsDtoMemoryUsage } from './containerStatsDtoMemoryUsage';
import { ContainerStatsDtoCpuPercent } from './containerStatsDtoCpuPercent';


export interface ContainerStatsPointDto { 
    timestamp: string;
    cpuPercent: ContainerStatsDtoCpuPercent;
    memoryUsage: ContainerStatsDtoMemoryUsage;
    memoryLimit: ContainerStatsDtoMemoryUsage;
    networkRx: ContainerStatsDtoMemoryUsage;
    networkTx: ContainerStatsDtoMemoryUsage;
}

