/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DeploymentTrigger = 'Create' | 'Manual' | 'Webhook' | 'Periodic' | 'Rollback' | 'ImageUpdate';

export const DeploymentTrigger = {

    Create: 'Create' as DeploymentTrigger,

    Manual: 'Manual' as DeploymentTrigger,

    Webhook: 'Webhook' as DeploymentTrigger,

    Periodic: 'Periodic' as DeploymentTrigger,

    Rollback: 'Rollback' as DeploymentTrigger,

    ImageUpdate: 'ImageUpdate' as DeploymentTrigger
};

