/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DeploymentStatus = 'Queued' | 'Running' | 'Succeeded' | 'Failed';

export const DeploymentStatus = {

    Queued: 'Queued' as DeploymentStatus,

    Running: 'Running' as DeploymentStatus,

    Succeeded: 'Succeeded' as DeploymentStatus,

    Failed: 'Failed' as DeploymentStatus
};

