/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiskUsageDtoImagesSize } from './diskUsageDtoImagesSize';


export interface DiskUsageDto { 
    imagesSize: DiskUsageDtoImagesSize | null;
    imagesReclaimable: DiskUsageDtoImagesSize | null;
    containersSize: DiskUsageDtoImagesSize | null;
    volumesSize: DiskUsageDtoImagesSize | null;
    volumesReclaimable: DiskUsageDtoImagesSize | null;
    buildCacheSize: DiskUsageDtoImagesSize | null;
}

