/**
 * DockiUp.API | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiskUsageDto { 
    imagesSize: number | null;
    imagesReclaimable: number | null;
    containersSize: number | null;
    volumesSize: number | null;
    volumesReclaimable: number | null;
    buildCacheSize: number | null;
}
