/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CleanupScheduleDtoHourUtc } from './cleanupScheduleDtoHourUtc';
import { DiskUsageDtoImagesSize } from './diskUsageDtoImagesSize';


export interface DockerVolumeDto { 
    name: string;
    driver: string;
    size: DiskUsageDtoImagesSize | null;
    created: string | null;
    containers: CleanupScheduleDtoHourUtc;
    inUse: boolean;
}

