/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CleanupScheduleDtoHourUtc } from './cleanupScheduleDtoHourUtc';
import { ContainerStatsDtoMemoryUsage } from './containerStatsDtoMemoryUsage';


export interface DockerImageDto { 
    id: string;
    tags: Array<string>;
    size: ContainerStatsDtoMemoryUsage;
    created: string;
    containers: CleanupScheduleDtoHourUtc;
    inUse: boolean;
    dangling: boolean;
}

