/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageProjectDto { 
    image: string;
    tag?: string | null;
    ports?: Array<string>;
    volumes?: Array<string>;
    environment?: Array<string>;
    restart?: string | null;
}

