/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InspectRepositoryRequest { 
    gitUrl: string;
    branch?: string | null;
    gitCredentialId?: string | null;
}

