/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CleanupScheduleDtoHourUtc } from './cleanupScheduleDtoHourUtc';


export interface NodePingResultDto { 
    reply: string;
    roundTripMs: CleanupScheduleDtoHourUtc;
}

