/**
 * DockiUp.API | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NotificationEvent = 'None' | 'DeploymentSucceeded' | 'DeploymentFailed' | 'NodeOffline' | 'NodeOnline' | 'ImageUpdateAvailable' | 'CleanupReport';

export const NotificationEvent = {

    None: 'None' as NotificationEvent,

    DeploymentSucceeded: 'DeploymentSucceeded' as NotificationEvent,

    DeploymentFailed: 'DeploymentFailed' as NotificationEvent,

    NodeOffline: 'NodeOffline' as NotificationEvent,

    NodeOnline: 'NodeOnline' as NotificationEvent,

    ImageUpdateAvailable: 'ImageUpdateAvailable' as NotificationEvent,

    CleanupReport: 'CleanupReport' as NotificationEvent
};

