/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContainerStatsDtoMemoryUsage } from './containerStatsDtoMemoryUsage';


export interface ProjectFileEntryDto { 
    name: string;
    path: string;
    isDirectory: boolean;
    size: ContainerStatsDtoMemoryUsage;
    modifiedAt: string;
    tracked: boolean;
}

