/**
 * DockiUp.API | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PruneResultDto { 
    containersDeleted: number;
    imagesDeleted: number;
    volumesDeleted: number;
    networksDeleted: number;
    spaceReclaimed: number;
}
