/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ResourceKind = 'Image' | 'Volume' | 'Network';

export const ResourceKind = {

    Image: 'Image' as ResourceKind,

    Volume: 'Volume' as ResourceKind,

    Network: 'Network' as ResourceKind
};

