/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeploymentDto } from './deploymentDto';


/**
 * <c>Tracked</c>: the file is versioned in git; <c>Commit</c>: the pushed commit (git projects); <c>Deployment</c>: the queued deployment when asked to deploy.
 */
export interface SaveProjectFileResultDto { 
    tracked: boolean;
    commit: string | null;
    deployment: DeploymentDto | null;
}

