/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CleanupScheduleDtoHourUtc } from './cleanupScheduleDtoHourUtc';
import { CleanupFrequency } from './cleanupFrequency';


export interface SaveCleanupScheduleCommand { 
    nodeId: string | null;
    frequency: CleanupFrequency;
    hourUtc: CleanupScheduleDtoHourUtc;
    dayOfWeekUtc: CleanupScheduleDtoHourUtc;
    pruneVolumes: boolean;
}
export namespace SaveCleanupScheduleCommand {
}


