/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageUpdatePolicy } from './imageUpdatePolicy';


export interface SetImageUpdateSettingsRequest { 
    policy: ImageUpdatePolicy;
    excludedServices: Array<string> | null;
}
export namespace SetImageUpdateSettingsRequest {
}


