/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatus } from './problemDetailsStatus';


export interface SetupProjectDto { 
    projectName: string;
    description?: string | null;
    projectOrigin: number;
    gitUrl?: string | null;
    branch?: string | null;
    composeFile?: string | null;
    compose?: string | null;
    path?: string | null;
    nodeId?: string | null;
    projectUpdateMethod: number;
    periodicIntervalInMinutes?: ProblemDetailsStatus | null;
}

