/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusType = 'Stopped' | 'Running' | 'Updating' | 'Failed' | 'NeedsUpdate';

export const StatusType = {

    Stopped: 'Stopped' as StatusType,

    Running: 'Running' as StatusType,

    Updating: 'Updating' as StatusType,

    Failed: 'Failed' as StatusType,

    NeedsUpdate: 'NeedsUpdate' as StatusType
};

