/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UpdateMethod = 0 | 1;

export const UpdateMethod = {

    NUMBER_0: 0 as UpdateMethod,

    NUMBER_1: 1 as UpdateMethod
};

