/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UpdateMethod = 'UseWebhook' | 'UpdateManually' | 'CheckPeriodically';

export const UpdateMethod = {

    UseWebhook: 'UseWebhook' as UpdateMethod,

    UpdateManually: 'UpdateManually' as UpdateMethod,

    CheckPeriodically: 'CheckPeriodically' as UpdateMethod
};

