/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSettingsDto } from './userSettingsDto';


export interface UpdateUserDto { 
    userId: number;
    username?: string | null;
    email?: string | null;
    profilePicture?: string | null;
    userSettings?: UserSettingsDto;
}

