/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColorScheme } from './colorScheme';


export interface UserSettingsDto { 
    userSettingsId?: number;
    preferredColorScheme: ColorScheme;
}
export namespace UserSettingsDto {
}


