/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'None' | 'User' | 'Admin';

export const UserRole = {

    None: 'None' as UserRole,

    User: 'User' as UserRole,

    Admin: 'Admin' as UserRole
};

