/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';
import { UserSettingsDto } from './userSettingsDto';


export interface UserDto { 
    userId?: number;
    username: string | null;
    email: string | null;
    profilePicture?: string | null;
    userSettings: UserSettingsDto;
    userRole: UserRole;
}
export namespace UserDto {
}


